<?php
$plugin = array(
  'title'     => t('Namu Site Template'),
  'theme'     => 'namu_site_template',
  'icon'      => 'namu_site_template.png',
  'category'  => 'Namu Site Templates',
  'regions' => array(
    'sidebar'     => t('Sidebar first'),
    'content'           => t('Main content'),
    'footer'            => t('Footer'),
    'header'            => t('Header'),
    'menu_bar'          => t('Menu Bar'),
    'help'              => t('Help'),
  ),
);


